project_id = "ygewodlugwtddrhswuvl"

[functions.optimize-title]
verify_jwt = false

[functions.generate-ideas]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.youtube-sync]
verify_jwt = false

[functions.scan-trends]
verify_jwt = false
